import { ThemeChange } from "../src/components/ThemeChanger";
import "../src/styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning={true} lang="en">
      <body className="relative">
        <div className="absolute right-5 top-5 z-10 p-8">
          <ThemeChange />
        </div>
        {children}
      </body>
    </html>
  );
}
