import { type NextPage } from "next";
import Head from "next/head";
import QuizSelection from "../src/components/QuizSelection";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Select Quiz</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex w-full min-h-screen justify-center items-center">
        <QuizSelection />
      </main>
    </>
  );
};

export default Home;
