import { type NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";
import { ThemeChange } from "../components/ThemeChanger";

const Quiz = dynamic(() => import("../components/Quiz"), {
  ssr: false,
});

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Test Hygiena</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex w-full justify-end p-8 ">
        <ThemeChange />
      </div>
      <main className="container mx-auto mt-32">
        <h1 className="mx-auto text-center text-4xl font-bold">Test Hygiena</h1>
        <Quiz />
      </main>
    </>
  );
};

export default Home;
